### PR TITLE
feat: hide upstream branches from logs

### LINKED ISSUE #32: omit branch names from output
Hey @wei 👋🏼 

The [current behavior](https://github.com/repo-sync/github-sync/blob/7c0db2f264834c5a01812e62c7e3f15c49634981/github-sync.sh#L37:L38) of this Action is to output every branch name in the logs:

```
echo "Fetching tmp_upstream"
git fetch tmp_upstream
```

For projects that have lots of branches, this produces a lot of output.

My request is that we add the `--quiet` flag to `git fetch tmp_upstream --quiet`, or add support for a parameter like `fetch_quietly` that can be specified in the workflow file and passed to the Action as an argument.

### PR DESCRIPTION
**Pull request by wei**
Fixes #32

### CODE REVIEW

**Review by zeke — APPROVED** [review]

**Comment by zeke** [comment]
That was quick!

**Comment by zeke** [comment]
What is the process for creating a new release?

**Comment by wei** [comment]
@zeke Now that we're using the brand new [GitHub Container Registry](https://github.com/orgs/repo-sync/packages/container/package/github-sync), release requires 3 steps

Let's say we're releasing `v2.2.2`
1. Edit `actions.yml` in `master` and update the docker image version to `v2.2.2`, [commit with message](https://github.com/repo-sync/github-sync/commit/414300b96807ec5f8bad3c16130259e392cfdeaf) `release: v2.2.2`
1. Go to [new release](https://github.com/repo-sync/github-sync/releases/new) to publish a new release, create a tag with `v2.2.2` @ `master`
1. Once `v2.2.2` is verified, we'll force push a `v2` tag to match `v2.2.2`

Step 1 is required because there is no automatic way of linking a actions release to a docker image release. We can definitely automate some of the steps in the future.

**Comment by wei** [comment]
Pushing tags will automatically trigger the deploy workflow which builds and pushes docker images at https://github.com/orgs/repo-sync/packages/container/package/github-sync

**Pull request merged**
